site_name: Coperlmçš„èŠå£«ğŸ§€åº“
site_url: https://coperlm.github.io/KnowledgeBase/
site_description: Knowledge Base of @coperlm

theme:
  name: material

# nav:
#   - Home: index.md
#   - About: about.md

plugins:
  # - git-revision-date-localized:  # æ˜¾ç¤ºæ–‡æ¡£çš„æœ€åä¿®æ”¹æ—¥æœŸ
  #     enable_creation_date: true  # å¯ç”¨åˆ›å»ºæ—¥æœŸæ˜¾ç¤º
  # - glightbox:  # å›¾ç‰‡æ˜¾ç¤ºæ’ä»¶ï¼Œç”¨äºæ˜¾ç¤ºå›¾åƒ
  - rss  # æ”¯æŒ RSS è®¢é˜…
  - search:  # å¯ç”¨æœç´¢åŠŸèƒ½
  - social:  # å¯ç”¨ç¤¾äº¤åª’ä½“å¡ç‰‡åŠŸèƒ½
      cards_layout_options:
        font_family: Noto Sans SC  # è®¾ç½®ç¤¾äº¤å¡ç‰‡å­—ä½“ä¸º Noto Sans SC
  - tags:  # å¯ç”¨æ ‡ç­¾åŠŸèƒ½
  - offline:  # ç¦»çº¿åŠŸèƒ½ï¼Œæ”¯æŒç¦»çº¿è®¿é—®
  - wavedrom:  # ç”¨äºæ˜¾ç¤ºæ³¢å½¢å›¾ï¼ˆé€‚ç”¨äºç”µå­å·¥ç¨‹ç›¸å…³å†…å®¹ï¼‰
      pymdownx: true  # å¯ç”¨ pymdownx æ‰©å±•

extra:
  analytics:
    provider: custom  # è‡ªå®šä¹‰åˆ†ææä¾›è€…
copyright: Copyright &copy; 2025-2025 Coperlm

repo_url: https://github.com/coperlm/KnowledgeBase

markdown_extensions:
  - attr_list  # å¯ç”¨ Markdown å±æ€§åˆ—è¡¨
  - md_in_html  # å¯ç”¨ Markdown ä¸­åµŒå…¥ HTML ä»£ç 
  - pymdownx.arithmatex:  # å¯ç”¨æ•°å­¦å…¬å¼æ”¯æŒ (LaTeX)
      generic: true  # å¯ç”¨æ ‡å‡†çš„ LaTeX è¯­æ³•
  - pymdownx.highlight:  # å¯ç”¨ä»£ç é«˜äº®
      anchor_linenums: true  # å¯ç”¨ä»£ç è¡Œå·
      line_spans: __span  # ç”¨äºæ ‡è®°ä»£ç è¡Œçš„ HTML ç±»å
      pygments_lang_class: true  # å¯ç”¨è¯­æ³•é«˜äº®
  - pymdownx.inlinehilite  # å¯ç”¨å†…è”é«˜äº®
  - pymdownx.snippets  # å¯ç”¨ä»£ç ç‰‡æ®µåŠŸèƒ½

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.1.0/skins/default.js
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.1.0/wavedrom.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

extra_css:
  - stylesheets/extra.css  # è‡ªå®šä¹‰æ ·å¼æ–‡ä»¶
