site_name: Coperlmçš„èŠå£«ğŸ§€åº“
site_url: https://coperlm.github.io/KnowledgeBase/
site_description: Knowledge Base of @coperlm

theme:
  name: material

# nav:
#   - Home: index.md
#   - About: about.md
